sudo: false

language: node_js

os:
  - linux
  - osx

node_js:
  - $NODE_VERSION

install:
  - npm remove node-gyp
  - yarn

script:
  - yarn package-binary
  - yarn publish-binary

after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  matrix:
    - NODE_VERSION="9"